services:
  - type: web
    name: debtease-server
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install .
      pip install ".[prod]"
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GROQ_API_KEY
        sync: false
      - key: LLM_PROVIDER
        value: groq
      - key: LLM_MODEL
        value: llama-3.1-8b-instant
      - key: DATABASE_URL
        fromDatabase:
          name: debtease-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: info
      - key: DEBUG
        value: false
      - key: CORS_ORIGINS
        value: "https://debt-flow-motion-53.vercel.app"
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: RATE_LIMIT_REQUESTS
        value: 100
      - key: RATE_LIMIT_WINDOW
        value: 60

databases:
  - name: debtease-db
    plan: free