services:
  - type: web
    name: debtease-server
    env: python
    plan: free
    buildCommand: pip install -e .
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false
      - key: LLM_PROVIDER
        value: groq
      - key: LLM_MODEL
        value: llama-3.1-8b-instant
      - key: DATABASE_URL
        fromDatabase:
          name: debtease-db
          property: connectionString
      - key: ENVIRONMENT
        value: production

databases:
  - name: debtease-db
    plan: free